<html>
<head>
        <meta charset="utf-8">
        <title>
                语言包测试
        </title>
        <script src="../../../public/js/jquery.min.js" type="text/javascript"></script>

</head>
<body>
<form action="Index/readLan" method="post" enctype="multipart/form-data">
        <input type="submit" value="读取文件" /><br/>
        <p><input type="file" name="file" onchange="check(this)" /></p>
</form>
<hr/>
<form id="compare" action="class/controller/compare.php" method="post" enctype="multipart/form-data">
        <p>
                <input type="submit" value="对比文件" />
                <input id="addCompare" type="button" value="增加对比文件"/>
        </p>
        <p><input type="file" name="compare[]" /></p>
        <p><input type="file" name="compare[]" /></p>
</form>
<hr/>
</body>
</html>
<script>
        var compare_num = 2;
        $('#addCompare').click(function() {
                compare_num++;
                $('#compare').append("<p><input type='file' name='compare[]'/></p>")
        });

        function check(obj) {
                var file = obj.files[0];
                console.log(obj.files[0]);
        }
</script>