<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <title>
        语言包测试
    </title>
    <script src="../../../public/js/jquery.min.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="../../../public/css/public.css">
    <style>

    </style>
</head>
<body class="position">
    <p><a class="btn button green render" onclick="goPower(1)">新增语言包</a></p>
    <p><a class="btn button green render" onclick="goPower(2)">修改语言包</a></p>
</body>
</html>
<script>
    function goPower(flag) {
        if(flag == 1) {
            window.location.href = "Index/addLanPackagePage";
            return;
        }
        if(flag == 2) {
            window.location.href = "Index/editLanPackagePage";
        }
    }
</script>